<?php
if ($block->getData('text_field')) {
    echo "<h3><strong>" . $block->getData('text_field') . "</strong></h3>";
}
?>
<ul>
    <?php $cmsPages = $block->getCmsPageCollection(); ?>
    <?php $sites = $block->getData('sites'); ?>

    <?php if($sites) { ?>

        <?php $siteExplode = explode(',', $sites) ?>

        <?php foreach($siteExplode as $site) { ?>
            <li> 
                <a href="<?= $site ?>">
                    <?= $site ?> 
                </a>
            </li>
        <?php } ?>
    <?php }

    elseif($block->getData('dropdown_field')) { ?>
        <?php foreach ($cmsPages as $cmsPage) { ?>
            <li>
                <a href="<?=$cmsPage->getIdentifier() ?>">
                    <?php echo $cmsPage->getTitle() ?>
                </a>
            </li>
        <?php } ?>
    <?php } ?>
</ul>
    
<?php 


?>

<!-- foreach get datasites  as sites  
model cms page api
explode 'sites' ?
 -->