<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $collection = $block->getQuestions(); ?>
        <h1>Frequently Asked Questions</h1>
        <?php foreach ($collection as $item) { ?>
            <div data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true}}'>
                <div data-role="collapsible" >
                    <div data-role="trigger" >
                        <div data-th="<?= $block->escapeHtml(__('Question')) ?>" class="col question">
                            <?= $block->escapeHtml($item->getQuestion()) ?>
                        </div>
                    </div>
                </div>
                <div data-role="content">
                    <p>
                        <div data-th="<?= $block->escapeHtml(__('Answer')) ?>" class="col answer">
                            <?= $block->escapeHtml($item->getAnswer()); ?>
                        </div>
                    </p>
                </div>
            </div>
    <?php } ?>

