<?php

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<div class="product-secure-logos-holder">
    <?php if ($block->getData('path_image')): ?>
        <div class="product-secure-title">
        </div>
        <div class="product-secure-logos">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl($block->getData('path_image'))); ?>"/>
        </div>
    <?php endif; ?>
</div>