<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <?php if($_product->getTypeId() == 'simple'): ?>
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">

                    <div class="control">
            <span style="
            border: 1px solid #C2C2C2;
            border-radius: 2px 0px 0px 2px;
            opacity: 1;
            padding: 0px 25px 10.5px;
            font-size: 28px;
            cursor: pointer;
            width: 10px;
            height: 2px;
            transform: matrix(0, 1, -1, 0, 0, 0);"
                  class="quantity-controls quantity-minus">-</span>
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="qty-default input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <span
                            style="
                        border: 1px solid #C2C2C2;
                        border-radius: 0px 2px 2px 0px;
                        opacity: 1;
                        padding: 8.5px 25px 13px;
                        font-size: 20px;
                        cursor: pointer;
                        color: #FF5501;"
                            class="quantity-controls quantity-plus">+</span>

                        <div class="control-qty">
                            <script type="text/javascript">
                                require([
                                    'jquery'
                                ], function ($) {
                                    $('.quantity-plus').click(function () {
                                        $('.qty-default').val(Number($('.qty-default').val()) + 1);
                                    });

                                    $('.quantity-minus').click(function () {
                                        var value = Number($('.qty-default').val()) - 1;
                                        if (value > 0) {
                                            $('.qty-default').val(value);
                                        }

                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart simple-product-button"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
        <?php else: ?>
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <label  class="label" for="qty"><span style="height: 20px; width: 100px" ><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart no-simple-product-button"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    <?php endif; ?>

</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
